import test from "node:test";
import assert from "node:assert/strict";
import { getLinkedinUrl, extractLinkedinId, parseFollowersCount } from "../utils/linkedin-utils.ts";

test("getLinkedinUrl", () => {
  assert.strictEqual(getLinkedinUrl("google"), "https://linkedin.com/company/google");
  assert.strictEqual(getLinkedinUrl("intuit"), "https://linkedin.com/company/intuit");
  assert.strictEqual(getLinkedinUrl("microsoft"), "https://linkedin.com/company/microsoft");
  assert.strictEqual(getLinkedinUrl("apple"), "https://linkedin.com/company/apple");
  assert.strictEqual(getLinkedinUrl("amazon"), "https://linkedin.com/company/amazon");
  assert.strictEqual(getLinkedinUrl("facebook"), "https://linkedin.com/company/facebook");
});

test("extractLinkedinId", () => {
  assert.strictEqual(extractLinkedinId(""), null);
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com"), null);
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/company/"), null);
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/profile/hazem"), null);
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/company/google"), "google");
  assert.strictEqual(extractLinkedinId("https://au.linkedin.com/company/intuit"), "intuit");
  assert.strictEqual(extractLinkedinId("https://uk.linkedin.com/company/intuit"), "intuit");
  assert.strictEqual(extractLinkedinId("https://linkedin.com/company/microsoft/"), "microsoft");
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/company/apple?trk=public_profile"), "apple");
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/company/amazon#about"), "amazon");
  assert.strictEqual(extractLinkedinId("https://www.linkedin.com/company/facebook/"), "facebook");
  assert.strictEqual(extractLinkedinId("https://linkedin.com/company/apple?trk=public_profile"), "apple");
  assert.strictEqual(extractLinkedinId("https://linkedin.com/company/amazon#about"), "amazon");
  assert.strictEqual(extractLinkedinId("https://linkedin.com/company/facebook/"), "facebook");
});

test("parseFollowersCount", () => {
  assert.strictEqual(parseFollowersCount(""), -1);
  assert.strictEqual(parseFollowersCount("https://www.linkedin.com"), -1);
  assert.strictEqual(parseFollowersCount("https://www.linkedin.com > about"), -1);
  assert.strictEqual(parseFollowersCount("https://www.linkedin.com > follower"), -1);
  assert.strictEqual(parseFollowersCount("https://www.linkedin.com > followers"), -1);
  assert.strictEqual(parseFollowersCount("No followers"), -1);
  assert.strictEqual(parseFollowersCount("No available linkedin followers"), -1);
  assert.strictEqual(parseFollowersCount("5 followers"), 5);
  assert.strictEqual(parseFollowersCount("1.2k followers"), 1200);
  assert.strictEqual(parseFollowersCount("3.5M followers"), 3500000);
  assert.strictEqual(parseFollowersCount("2.1B followers"), 2100000000);
  assert.strictEqual(parseFollowersCount("10+ followers"), 10);
  assert.strictEqual(parseFollowersCount("1000 followers"), 1000);
  assert.strictEqual(parseFollowersCount("11.8M+ followers"), 11800000);
  assert.strictEqual(parseFollowersCount("194.5K+ followers"), 194500);
  assert.strictEqual(parseFollowersCount("361K+ followers"), 361000);
  assert.strictEqual(parseFollowersCount("640+ followers"), 640);
  assert.strictEqual(parseFollowersCount("410.4K+ followers"), 410400);
  assert.strictEqual(parseFollowersCount("11.1K+ followers"), 11100);
  assert.strictEqual(parseFollowersCount("1.1K+ followers"), 1100);
  assert.strictEqual(parseFollowersCount("16.8K+ followers"), 16800);
  assert.strictEqual(parseFollowersCount("14K+ followers"), 14000);
  assert.strictEqual(parseFollowersCount("14K followers"), 14000);
  assert.strictEqual(parseFollowersCount("14000 followers"), 14000);
  assert.strictEqual(parseFollowersCount("5.5K+ followers"), 5500);
  assert.strictEqual(parseFollowersCount("6K+ followers"), 6000);
  assert.strictEqual(parseFollowersCount("530+ followers"), 530);
  assert.strictEqual(parseFollowersCount("6 followers"), 6);
  assert.strictEqual(parseFollowersCount("0 followers"), 0);
  assert.strictEqual(parseFollowersCount("0 follower"), 0);
  assert.strictEqual(parseFollowersCount("1 follower"), 1);
  assert.strictEqual(parseFollowersCount("1 linkedin follower"), 1);
  assert.strictEqual(parseFollowersCount("10k+ linkedin followers"), 10000);
  assert.strictEqual(parseFollowersCount("80+ followers"), 80);
  assert.strictEqual(parseFollowersCount("1.5K+ followers"), 1500);
  assert.strictEqual(parseFollowersCount("267K+ followers"), 267000);
  assert.strictEqual(parseFollowersCount("128.2K+ followers"), 128200);
  assert.strictEqual(parseFollowersCount("46.9K+ followers"), 46900);
  assert.strictEqual(parseFollowersCount("18.2K+ followers"), 18200);
  assert.strictEqual(parseFollowersCount("46.8K+ followers"), 46800);
  assert.strictEqual(parseFollowersCount("the company has 472,246 LinkedIn followers"), 472246);
});
