export const CATEGORIES_MAP = {
  frontend: { id: "frontend", label: "Frontend Engineer" },
  backend: { id: "backend", label: "Backend Engineer" },
  fullstack: { id: "fullstack", label: "Fullstack Engineer" },
  devops: { id: "devops", label: "DevOps Engineer" },
} as const;

export const SENIORITY_MAP = {
  entry: { id: "entry-level", seniorityLabel: "Entry-Level", yearsLabel: "(0 years)" },
  junior: { id: "junior-level", seniorityLabel: "Junior-Level", yearsLabel: "(1-2 years)" },
  mid: { id: "mid-level", seniorityLabel: "Mid-Level", yearsLabel: "(3-5 years)" },
  senior: { id: "senior-level", seniorityLabel: "Senior-Level", yearsLabel: "(7+ years)" },
  lead: { id: "lead-level", seniorityLabel: "Lead-Level", yearsLabel: "(8+ years)" },
} as const;

export const WORKPLACE_TYPES_MAP = {
  onsite: { id: "on-site", label: "On Site" },
  remote: { id: "remote", label: "Remote" },
  hybrid: { id: "hybrid", label: "Hybrid" },
} as const;

export const EMPLOYMENT_TYPES_MAP = {
  fulltime: { id: "full-time", label: "Full Time" },
  parttime: { id: "part-time", label: "Part Time" },
  contract: { id: "contract", label: "Contract" },
  internship: { id: "internship", label: "Internship" },
} as const;

export const CURRENCIES_MAP = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  CAD: "C$",
  AUD: "A$",
  CHF: "CHF",
  CNY: "¥",
  SEK: "kr",
  NZD: "NZ$",
  JPY: "¥",
  RUB: "₽",
  INR: "₹",
  BRL: "R$",
  ZAR: "R",
} as const;

export const WORLDWIDE_LOCATIONS_MAP = {
  worldwide: {
    id: "worldwide",
    label: "Worldwide",
    aliases: [],
    search: { remote: "", onSiteOrHybrid: "" },
  },
} as const;

export const BUSINESS_REGIONS_MAP = {
  emea: {
    id: "emea",
    label: "EMEA",
    aliases: ["emea", "europe middle east africa", "europe, middle east and africa"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "businessRegion:emea" },
  },
  apac: {
    id: "apac",
    label: "APAC",
    aliases: ["apac", "asia pacific", "asia-pacific"],
    search: { remote: "businessRegion:apac", onSiteOrHybrid: "businessRegion:apac" },
  },
  amer: {
    id: "amer",
    label: "AMER",
    aliases: ["amer", "americas", "north and south america", "north america and south america"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "businessRegion:amer" },
  },
};

export const CONTINENTS_MAP = {
  northamerica: {
    id: "northamerica",
    label: "North America",
    aliases: ["northamerica", "north america", "na", "n.a.", "n. america"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "continent:northamerica" },
    businessRegion: "amer",
  },
  southamerica: {
    id: "southamerica",
    label: "South America",
    aliases: ["southamerica", "south america", "sa", "s.a.", "s. america"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "continent:southamerica" },
    businessRegion: "amer",
  },
  europe: {
    id: "europe",
    label: "Europe",
    aliases: ["europe", "eu", "european union", "europe continent", "eurasia west", "schengen area (partial)"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "continent:europe" },
    businessRegion: "emea",
  },
  asia: {
    id: "asia",
    label: "Asia",
    aliases: ["asia", "as", "asian continent"],
    search: { remote: "businessRegion:apac", onSiteOrHybrid: "continent:asia" },
    businessRegion: "apac",
  },
  africa: {
    id: "africa",
    label: "Africa",
    aliases: ["africa", "af", "african continent"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "continent:africa" },
    businessRegion: "emea",
  },
  oceania: {
    id: "oceania",
    label: "Oceania",
    aliases: ["oceania", "oc", "australia and oceania"],
    search: { remote: "businessRegion:apac", onSiteOrHybrid: "continent:oceania" },
    businessRegion: "apac",
  },
} as const;

export const COUNTRIES_MAP = {
  unitedstates: {
    id: "unitedstates",
    label: "United States",
    aliases: ["united states", "usa", "us", "u.s.a", "u.s.", "united states of america", "america"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "country:unitedstates" },
    businessRegion: "amer",
    continent: "northamerica",
  },
  canada: {
    id: "canada",
    label: "Canada",
    aliases: ["canada", "ca", "can", "ca canada", "dominions of canada"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "country:canada" },
    businessRegion: "amer",
    continent: "northamerica",
  },
  brazil: {
    id: "brazil",
    label: "Brazil",
    aliases: ["brazil"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "country:brazil" },
    businessRegion: "amer",
    continent: "southamerica",
  },
  france: {
    id: "france",
    label: "France",
    aliases: ["france", "fr", "french republic", "république française", "france eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:france" },
    businessRegion: "emea",
    continent: "europe",
  },
  italy: {
    id: "italy",
    label: "Italy",
    aliases: ["italy", "it", "italian republic", "repubblica italiana", "italy eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:italy" },
    businessRegion: "emea",
    continent: "europe",
  },
  germany: {
    id: "germany",
    label: "Germany",
    aliases: ["germany", "de", "deutschland", "federal republic of germany", "bundesrepublik deutschland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:germany" },
    businessRegion: "emea",
    continent: "europe",
  },
  unitedkingdom: {
    id: "unitedkingdom",
    label: "United Kingdom",
    aliases: ["united kingdom", "uk", "u.k.", "great britain", "britain"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:unitedkingdom" },
    businessRegion: "emea",
    continent: "europe",
  },
  spain: {
    id: "spain",
    label: "Spain",
    aliases: ["spain", "es", "espana", "españa", "kingdom of spain", "spain eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:spain" },
    businessRegion: "emea",
    continent: "europe",
  },
  netherlands: {
    id: "netherlands",
    label: "Netherlands",
    aliases: ["netherlands", "nl", "holland", "the netherlands", "nederland", "netherlands eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:netherlands" },
    businessRegion: "emea",
    continent: "europe",
  },
  portugal: {
    id: "portugal",
    label: "Portugal",
    aliases: ["portugal", "pt", "portuguese republic", "república portuguesa", "portugal eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:portugal" },
    businessRegion: "emea",
    continent: "europe",
  },
  belgium: {
    id: "belgium",
    label: "Belgium",
    aliases: ["belgium", "be", "belgique", "belgie", "belgië", "kingdom of belgium", "belgium eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:belgium" },
    businessRegion: "emea",
    continent: "europe",
  },
  switzerland: {
    id: "switzerland",
    label: "Switzerland",
    aliases: ["switzerland", "ch", "swiss", "schweiz", "suisse", "svizzera", "swiss confederation"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:switzerland" },
    businessRegion: "emea",
    continent: "europe",
  },
  austria: {
    id: "austria",
    label: "Austria",
    aliases: ["austria", "at", "osterreich", "österreich", "republic of austria", "austria eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:austria" },
    businessRegion: "emea",
    continent: "europe",
  },
  ireland: {
    id: "ireland",
    label: "Ireland",
    aliases: ["ireland", "ie", "eire", "éire", "republic of ireland", "ireland eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:ireland" },
    businessRegion: "emea",
    continent: "europe",
  },
  sweden: {
    id: "sweden",
    label: "Sweden",
    aliases: ["sweden", "se", "sverige", "kingdom of sweden", "sweden eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:sweden" },
    businessRegion: "emea",
    continent: "europe",
  },
  norway: {
    id: "norway",
    label: "Norway",
    aliases: ["norway", "no", "norge", "kingdom of norway"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:norway" },
    businessRegion: "emea",
    continent: "europe",
  },
  denmark: {
    id: "denmark",
    label: "Denmark",
    aliases: ["denmark", "dk", "danmark", "kingdom of denmark", "denmark eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:denmark" },
    businessRegion: "emea",
    continent: "europe",
  },
  finland: {
    id: "finland",
    label: "Finland",
    aliases: ["finland", "fi", "suomi", "republic of finland", "finland eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:finland" },
    businessRegion: "emea",
    continent: "europe",
  },
  poland: {
    id: "poland",
    label: "Poland",
    aliases: ["poland", "pl", "polska", "republic of poland", "poland eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:poland" },
    businessRegion: "emea",
    continent: "europe",
  },
  czechrepublic: {
    id: "czechrepublic",
    label: "Czech Republic",
    aliases: ["czech republic", "cz", "czechia", "cesko", "česko", "czech republic eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:czechrepublic" },
    businessRegion: "emea",
    continent: "europe",
  },
  romania: {
    id: "romania",
    label: "Romania",
    aliases: ["romania", "ro", "românia", "romania eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:romania" },
    businessRegion: "emea",
    continent: "europe",
  },
  hungary: {
    id: "hungary",
    label: "Hungary",
    aliases: ["hungary", "hu", "magyarorszag", "magyarország", "hungary eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:hungary" },
    businessRegion: "emea",
    continent: "europe",
  },
  greece: {
    id: "greece",
    label: "Greece",
    aliases: ["greece", "gr", "hellas", "hellenic republic", "greece eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:greece" },
    businessRegion: "emea",
    continent: "europe",
  },
  ukraine: {
    id: "ukraine",
    label: "Ukraine",
    aliases: ["ukraine", "ua", "ukraina", "україна"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:ukraine" },
    businessRegion: "emea",
    continent: "europe",
  },
  croatia: {
    id: "croatia",
    label: "Croatia",
    aliases: ["croatia", "hr", "hrvatska", "republic of croatia", "croatia eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:croatia" },
    businessRegion: "emea",
    continent: "europe",
  },
  slovakia: {
    id: "slovakia",
    label: "Slovakia",
    aliases: ["slovakia", "sk", "slovensko", "slovak republic", "slovakia eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:slovakia" },
    businessRegion: "emea",
    continent: "europe",
  },
  slovenia: {
    id: "slovenia",
    label: "Slovenia",
    aliases: ["slovenia", "si", "slovenija", "republic of slovenia", "slovenia eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:slovenia" },
    businessRegion: "emea",
    continent: "europe",
  },
  bulgaria: {
    id: "bulgaria",
    label: "Bulgaria",
    aliases: ["bulgaria", "bg", "balgariya", "bulgarian republic", "bulgaria eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:bulgaria" },
    businessRegion: "emea",
    continent: "europe",
  },
  lithuania: {
    id: "lithuania",
    label: "Lithuania",
    aliases: ["lithuania", "lt", "lietuva", "republic of lithuania", "lithuania eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:lithuania" },
    businessRegion: "emea",
    continent: "europe",
  },
  latvia: {
    id: "latvia",
    label: "Latvia",
    aliases: ["latvia", "lv", "latvija", "republic of latvia", "latvia eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:latvia" },
    businessRegion: "emea",
    continent: "europe",
  },
  estonia: {
    id: "estonia",
    label: "Estonia",
    aliases: ["estonia", "ee", "eesti", "republic of estonia", "estonia eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:estonia" },
    businessRegion: "emea",
    continent: "europe",
  },
  luxembourg: {
    id: "luxembourg",
    label: "Luxembourg",
    aliases: ["luxembourg", "lu", "letzebuerg", "lëtzebuerg", "grand duchy of luxembourg", "luxembourg eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:luxembourg" },
    businessRegion: "emea",
    continent: "europe",
  },
  iceland: {
    id: "iceland",
    label: "Iceland",
    aliases: ["iceland", "is", "island", "ísland", "republic of iceland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:iceland" },
    businessRegion: "emea",
    continent: "europe",
  },
  serbia: {
    id: "serbia",
    label: "Serbia",
    aliases: ["serbia", "rs", "srbija", "republic of serbia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:serbia" },
    businessRegion: "emea",
    continent: "europe",
  },
  malta: {
    id: "malta",
    label: "Malta",
    aliases: ["malta", "mt", "republic of malta", "malta eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:malta" },
    businessRegion: "emea",
    continent: "europe",
  },
  cyprus: {
    id: "cyprus",
    label: "Cyprus",
    aliases: ["cyprus", "cy", "republic of cyprus", "cyprus eu"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "country:cyprus" },
    businessRegion: "emea",
    continent: "europe",
  },
} as const;

export const CITIES_MAP = {
  // USA
  newyork: {
    id: "newyork",
    label: "New York",
    aliases: ["new york", "new york city", "nyc", "ny"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:newyork" },
  },
  losangeles: {
    id: "losangeles",
    label: "Los Angeles",
    aliases: ["los angeles", "la", "l.a."],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:losAngeles" },
  },
  chicago: {
    id: "chicago",
    label: "Chicago",
    aliases: ["chicago", "chi-town"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:chicago" },
  },
  houston: {
    id: "houston",
    label: "Houston",
    aliases: ["houston", "houston tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:houston" },
  },
  phoenix: {
    id: "phoenix",
    label: "Phoenix",
    aliases: ["phoenix", "phoenix az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:phoenix" },
  },
  philadelphia: {
    id: "philadelphia",
    label: "Philadelphia",
    aliases: ["philadelphia", "philly"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:philadelphia" },
  },
  sanAntonio: {
    id: "sanAntonio",
    label: "San Antonio",
    aliases: ["san antonio", "san antonio tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sanAntonio" },
  },
  sandiego: {
    id: "sandiego",
    label: "San Diego",
    aliases: ["san diego", "sd"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sanDiego" },
  },
  dallas: {
    id: "dallas",
    label: "Dallas",
    aliases: ["dallas", "dallas tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:dallas" },
  },
  austin: {
    id: "austin",
    label: "Austin",
    aliases: ["austin", "austin tx", "atx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:austin" },
  },
  sanJose: {
    id: "sanJose",
    label: "San Jose",
    aliases: ["san jose", "san jose ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sanJose" },
  },
  jacksonville: {
    id: "jacksonville",
    label: "Jacksonville",
    aliases: ["jacksonville", "jacksonville fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:jacksonville" },
  },
  fortworth: {
    id: "fortworth",
    label: "Fort Worth",
    aliases: ["fort worth", "ft worth"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:fortWorth" },
  },
  columbus: {
    id: "columbus",
    label: "Columbus",
    aliases: ["columbus", "columbus oh"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:columbus" },
  },
  charlotte: {
    id: "charlotte",
    label: "Charlotte",
    aliases: ["charlotte", "charlotte nc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:charlotte" },
  },
  sanfrancisco: {
    id: "sanfrancisco",
    label: "San Francisco",
    aliases: ["san francisco", "sf", "bay area", "san francisco bay area"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sanFrancisco" },
  },
  indianapolis: {
    id: "indianapolis",
    label: "Indianapolis",
    aliases: ["indianapolis", "indy"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:indianapolis" },
  },
  seattle: {
    id: "seattle",
    label: "Seattle",
    aliases: ["seattle", "seattle wa"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:seattle" },
  },
  denver: {
    id: "denver",
    label: "Denver",
    aliases: ["denver", "denver co"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:denver" },
  },
  washington: {
    id: "washington",
    label: "Washington, DC",
    aliases: ["washington dc", "dc", "d.c.", "washington"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:washington" },
  },
  boston: {
    id: "boston",
    label: "Boston",
    aliases: ["boston", "boston ma"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:boston" },
  },
  elpaso: {
    id: "elpaso",
    label: "El Paso",
    aliases: ["el paso", "el paso tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:elpaso" },
  },
  nashville: {
    id: "nashville",
    label: "Nashville",
    aliases: ["nashville", "nashville tn"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:nashville" },
  },
  detroit: {
    id: "detroit",
    label: "Detroit",
    aliases: ["detroit", "detroit mi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:detroit" },
  },
  oklahomaCity: {
    id: "oklahomaCity",
    label: "Oklahoma City",
    aliases: ["oklahoma city", "okc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:oklahomaCity" },
  },
  portland: {
    id: "portland",
    label: "Portland",
    aliases: ["portland", "portland or"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:portland" },
  },
  lasvegas: {
    id: "lasvegas",
    label: "Las Vegas",
    aliases: ["las vegas", "vegas"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:lasvegas" },
  },
  memphis: {
    id: "memphis",
    label: "Memphis",
    aliases: ["memphis", "memphis tn"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:memphis" },
  },
  louisville: {
    id: "louisville",
    label: "Louisville",
    aliases: ["louisville", "louisville ky"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:louisville" },
  },
  baltimore: {
    id: "baltimore",
    label: "Baltimore",
    aliases: ["baltimore", "baltimore md"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:baltimore" },
  },
  milwaukee: {
    id: "milwaukee",
    label: "Milwaukee",
    aliases: ["milwaukee", "milwaukee wi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:milwaukee" },
  },
  albuquerque: {
    id: "albuquerque",
    label: "Albuquerque",
    aliases: ["albuquerque", "abq"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:albuquerque" },
  },
  tucson: {
    id: "tucson",
    label: "Tucson",
    aliases: ["tucson", "tucson az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:tucson" },
  },
  fresno: {
    id: "fresno",
    label: "Fresno",
    aliases: ["fresno", "fresno ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:fresno" },
  },
  sacramento: {
    id: "sacramento",
    label: "Sacramento",
    aliases: ["sacramento", "sac"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sacramento" },
  },
  kansasCity: {
    id: "kansasCity",
    label: "Kansas City",
    aliases: ["kansas city", "kc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:kansasCity" },
  },
  atlanta: {
    id: "atlanta",
    label: "Atlanta",
    aliases: ["atlanta", "atl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:atlanta" },
  },
  miami: {
    id: "miami",
    label: "Miami",
    aliases: ["miami", "miami fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:miami" },
  },
  orlando: {
    id: "orlando",
    label: "Orlando",
    aliases: ["orlando", "orlando fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:orlando" },
  },
  tampa: {
    id: "tampa",
    label: "Tampa",
    aliases: ["tampa", "tampa fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:tampa" },
  },
  newOrleans: {
    id: "newOrleans",
    label: "New Orleans",
    aliases: ["new orleans", "nola"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:newOrleans" },
  },
  cleveland: {
    id: "cleveland",
    label: "Cleveland",
    aliases: ["cleveland", "cleveland oh"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:cleveland" },
  },
  pittsburgh: {
    id: "pittsburgh",
    label: "Pittsburgh",
    aliases: ["pittsburgh", "pgh"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:pittsburgh" },
  },
  cincinnati: {
    id: "cincinnati",
    label: "Cincinnati",
    aliases: ["cincinnati", "cincy"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:cincinnati" },
  },
  raleigh: {
    id: "raleigh",
    label: "Raleigh",
    aliases: ["raleigh", "raleigh nc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:raleigh" },
  },
  saltLakecity: {
    id: "saltLakecity",
    label: "Salt Lake City",
    aliases: ["salt lake city", "slc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:saltLakecity" },
  },
  minneapolis: {
    id: "minneapolis",
    label: "Minneapolis",
    aliases: ["minneapolis", "minneapolis mn"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:minneapolis" },
  },
  honolulu: {
    id: "honolulu",
    label: "Honolulu",
    aliases: ["honolulu", "honolulu hi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:honolulu" },
  },
  stLouis: {
    id: "stLouis",
    label: "St. Louis",
    aliases: ["st. louis", "st louis", "stl", "saint louis"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:stLouis" },
  },
  richmond: {
    id: "richmond",
    label: "Richmond",
    aliases: ["richmond", "richmond va"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:richmond" },
  },
  omaha: {
    id: "omaha",
    label: "Omaha",
    aliases: ["omaha", "omaha ne"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:omaha" },
  },
  tulsa: {
    id: "tulsa",
    label: "Tulsa",
    aliases: ["tulsa", "tulsa ok"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:tulsa" },
  },
  riverside: {
    id: "riverside",
    label: "Riverside",
    aliases: ["riverside", "riverside ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:riverside" },
  },
  mesa: {
    id: "mesa",
    label: "Mesa",
    aliases: ["mesa", "mesa az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:mesa" },
  },
  virginiaBeach: {
    id: "virginiaBeach",
    label: "Virginia Beach",
    aliases: ["virginia beach", "virginia beach va"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:virginiaBeach" },
  },
  coloradoSprings: {
    id: "coloradoSprings",
    label: "Colorado Springs",
    aliases: ["colorado springs", "colorado springs co"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:coloradoSprings" },
  },
  arlingtonTx: {
    id: "arlingtonTx",
    label: "Arlington, TX",
    aliases: ["arlington tx", "arlington texas"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:arlingtonTx" },
  },
  wichita: {
    id: "wichita",
    label: "Wichita",
    aliases: ["wichita", "wichita ks"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:wichita" },
  },
  anaheim: {
    id: "anaheim",
    label: "Anaheim",
    aliases: ["anaheim", "anaheim ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:anaheim" },
  },
  corpusChristi: {
    id: "corpusChristi",
    label: "Corpus Christi",
    aliases: ["corpus christi", "corpus christi tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:corpusChristi" },
  },
  lexington: {
    id: "lexington",
    label: "Lexington",
    aliases: ["lexington", "lexington ky"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:lexington" },
  },
  henderson: {
    id: "henderson",
    label: "Henderson",
    aliases: ["henderson", "henderson nv"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:henderson" },
  },
  stockton: {
    id: "stockton",
    label: "Stockton",
    aliases: ["stockton", "stockton ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:stockton" },
  },
  saintPaul: {
    id: "saintPaul",
    label: "Saint Paul",
    aliases: ["saint paul", "st. paul", "st paul", "saint paul mn"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:saintPaul" },
  },
  stPetersburg: {
    id: "stPetersburg",
    label: "St. Petersburg",
    aliases: ["st. petersburg", "st petersburg", "st. petersburg fl", "st petersburg fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:stPetersburg" },
  },
  plano: {
    id: "plano",
    label: "Plano",
    aliases: ["plano", "plano tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:plano" },
  },
  irvine: {
    id: "irvine",
    label: "Irvine",
    aliases: ["irvine", "irvine ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:irvine" },
  },
  newark: {
    id: "newark",
    label: "Newark",
    aliases: ["newark", "newark nj"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:newark" },
  },
  durham: {
    id: "durham",
    label: "Durham",
    aliases: ["durham", "durham nc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:durham" },
  },
  chulaVista: {
    id: "chulaVista",
    label: "Chula Vista",
    aliases: ["chula vista", "chula vista ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:chulaVista" },
  },
  toledo: {
    id: "toledo",
    label: "Toledo",
    aliases: ["toledo", "toledo oh"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:toledo" },
  },
  madison: {
    id: "madison",
    label: "Madison",
    aliases: ["madison", "madison wi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:madison" },
  },
  reno: {
    id: "reno",
    label: "Reno",
    aliases: ["reno", "reno nv"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:reno" },
  },
  lubbock: {
    id: "lubbock",
    label: "Lubbock",
    aliases: ["lubbock", "lubbock tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:lubbock" },
  },
  gilbert: {
    id: "gilbert",
    label: "Gilbert",
    aliases: ["gilbert", "gilbert az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:gilbert" },
  },
  glendaleAz: {
    id: "glendaleAz",
    label: "Glendale, AZ",
    aliases: ["glendale az", "glendale arizona"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:glendaleAz" },
  },
  northLasVegas: {
    id: "northLasVegas",
    label: "North Las Vegas",
    aliases: ["north las vegas", "north las vegas nv"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:northLasVegas" },
  },
  chandler: {
    id: "chandler",
    label: "Chandler",
    aliases: ["chandler", "chandler az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:chandler" },
  },
  scottsdale: {
    id: "scottsdale",
    label: "Scottsdale",
    aliases: ["scottsdale", "scottsdale az"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:scottsdale" },
  },
  buffalo: {
    id: "buffalo",
    label: "Buffalo",
    aliases: ["buffalo", "buffalo ny"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:buffalo" },
  },
  chesapeake: {
    id: "chesapeake",
    label: "Chesapeake",
    aliases: ["chesapeake", "chesapeake va"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:chesapeake" },
  },
  norfolk: {
    id: "norfolk",
    label: "Norfolk",
    aliases: ["norfolk", "norfolk va"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:norfolk" },
  },
  garland: {
    id: "garland",
    label: "Garland",
    aliases: ["garland", "garland tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:garland" },
  },
  boise: {
    id: "boise",
    label: "Boise",
    aliases: ["boise", "boise id"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:boise" },
  },
  spokane: {
    id: "spokane",
    label: "Spokane",
    aliases: ["spokane", "spokane wa"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:spokane" },
  },
  batonRouge: {
    id: "batonRouge",
    label: "Baton Rouge",
    aliases: ["baton rouge", "baton rouge la"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:batonRouge" },
  },
  tacoma: {
    id: "tacoma",
    label: "Tacoma",
    aliases: ["tacoma", "tacoma wa"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:tacoma" },
  },
  irving: {
    id: "irving",
    label: "Irving",
    aliases: ["irving", "irving tx"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:irving" },
  },
  hialeah: {
    id: "hialeah",
    label: "Hialeah",
    aliases: ["hialeah", "hialeah fl"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:hialeah" },
  },
  rochesterNy: {
    id: "rochesterNy",
    label: "Rochester, NY",
    aliases: ["rochester ny", "rochester new york"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:rochesterNy" },
  },
  akron: {
    id: "akron",
    label: "Akron",
    aliases: ["akron", "akron oh"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:akron" },
  },
  fayetteville: {
    id: "fayetteville",
    label: "Fayetteville",
    aliases: ["fayetteville", "fayetteville nc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:fayetteville" },
  },
  desMoines: {
    id: "desMoines",
    label: "Des Moines",
    aliases: ["des moines", "des moines ia"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:desMoines" },
  },
  grandRapids: {
    id: "grandRapids",
    label: "Grand Rapids",
    aliases: ["grand rapids", "grand rapids mi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:grandRapids" },
  },
  huntsville: {
    id: "huntsville",
    label: "Huntsville",
    aliases: ["huntsville", "huntsville al"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:huntsville" },
  },
  littleRock: {
    id: "littleRock",
    label: "Little Rock",
    aliases: ["little rock", "little rock ar"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:littleRock" },
  },
  knoxville: {
    id: "knoxville",
    label: "Knoxville",
    aliases: ["knoxville", "knoxville tn"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:knoxville" },
  },
  savannah: {
    id: "savannah",
    label: "Savannah",
    aliases: ["savannah", "savannah ga"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:savannah" },
  },
  charleston: {
    id: "charleston",
    label: "Charleston",
    aliases: ["charleston", "charleston sc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:charleston" },
  },
  annArbor: {
    id: "annArbor",
    label: "Ann Arbor",
    aliases: ["ann arbor", "ann arbor mi"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:annArbor" },
  },
  providence: {
    id: "providence",
    label: "Providence",
    aliases: ["providence", "providence ri"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:providence" },
  },
  hartford: {
    id: "hartford",
    label: "Hartford",
    aliases: ["hartford", "hartford ct"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:hartford" },
  },
  newHaven: {
    id: "newHaven",
    label: "New Haven",
    aliases: ["new haven", "new haven ct"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:newHaven" },
  },
  albany: {
    id: "albany",
    label: "Albany",
    aliases: ["albany", "albany ny"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:albany" },
  },
  syracuse: {
    id: "syracuse",
    label: "Syracuse",
    aliases: ["syracuse", "syracuse ny"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:syracuse" },
  },
  santaClara: {
    id: "santaClara",
    label: "Santa Clara",
    aliases: ["santa clara", "santa clara ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:santaClara" },
  },
  mountainView: {
    id: "mountainView",
    label: "Mountain View",
    aliases: ["mountain view", "mountain view ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:mountainView" },
  },
  paloAlto: {
    id: "paloAlto",
    label: "Palo Alto",
    aliases: ["palo alto", "palo alto ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:paloAlto" },
  },
  sunnyvale: {
    id: "sunnyvale",
    label: "Sunnyvale",
    aliases: ["sunnyvale", "sunnyvale ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:sunnyvale" },
  },
  redmond: {
    id: "redmond",
    label: "Redmond",
    aliases: ["redmond", "redmond wa"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:redmond" },
  },
  bellevue: {
    id: "bellevue",
    label: "Bellevue",
    aliases: ["bellevue", "bellevue wa"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:bellevue" },
  },
  cambridgeMa: {
    id: "cambridgeMa",
    label: "Cambridge, MA",
    aliases: ["cambridge ma", "cambridge massachusetts"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:cambridgeMa" },
  },
  arlingtonVa: {
    id: "arlingtonVa",
    label: "Arlington, VA",
    aliases: ["arlington va", "arlington virginia"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:arlingtonVa" },
  },
  alexandria: {
    id: "alexandria",
    label: "Alexandria",
    aliases: ["alexandria", "alexandria va"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:alexandria" },
  },
  jerseyCity: {
    id: "jerseyCity",
    label: "Jersey City",
    aliases: ["jersey city", "jersey city nj"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:jerseyCity" },
  },
  hoboken: {
    id: "hoboken",
    label: "Hoboken",
    aliases: ["hoboken", "hoboken nj"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:hoboken" },
  },
  naperville: {
    id: "naperville",
    label: "Naperville",
    aliases: ["naperville", "naperville il"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:naperville" },
  },
  fortLauderdale: {
    id: "fortLauderdale",
    label: "Fort Lauderdale",
    aliases: ["fort lauderdale", "fort lauderdale fl", "ft lauderdale"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:fortLauderdale" },
  },

  // CANADA
  // CANADA
  toronto: {
    id: "toronto",
    label: "Toronto",
    aliases: ["toronto", "toronto ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:toronto" },
  },
  montreal: {
    id: "montreal",
    label: "Montreal",
    aliases: ["montreal", "montréal", "montreal qc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:montreal" },
  },
  vancouver: {
    id: "vancouver",
    label: "Vancouver",
    aliases: ["vancouver", "vancouver bc"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:vancouver" },
  },
  calgary: {
    id: "calgary",
    label: "Calgary",
    aliases: ["calgary", "calgary ab"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:calgary" },
  },
  ottawa: {
    id: "ottawa",
    label: "Ottawa",
    aliases: ["ottawa", "ottawa ca"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:ottawa" },
  },

  // EUROPE
  london: {
    id: "london",
    label: "London",
    aliases: ["london", "london uk"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:london" },
  },
  paris: {
    id: "paris",
    label: "Paris",
    aliases: ["paris", "paris france", "paris fr"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:paris" },
  },
  berlin: {
    id: "berlin",
    label: "Berlin",
    aliases: ["berlin", "berlin germany"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:berlin" },
  },
  madrid: {
    id: "madrid",
    label: "Madrid",
    aliases: ["madrid", "madrid spain"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:madrid" },
  },
  barcelona: {
    id: "barcelona",
    label: "Barcelona",
    aliases: ["barcelona", "barcelona spain", "barça"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:barcelona" },
  },
  rome: {
    id: "rome",
    label: "Rome",
    aliases: ["rome", "roma", "rome italy"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:rome" },
  },
  milan: {
    id: "milan",
    label: "Milan",
    aliases: ["milan", "milano"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:milan" },
  },
  amsterdam: {
    id: "amsterdam",
    label: "Amsterdam",
    aliases: ["amsterdam", "amsterdam nl"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:amsterdam" },
  },
  brussels: {
    id: "brussels",
    label: "Brussels",
    aliases: ["brussels", "bruxelles"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:brussels" },
  },
  vienna: {
    id: "vienna",
    label: "Vienna",
    aliases: ["vienna", "wien"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:vienna" },
  },
  prague: {
    id: "prague",
    label: "Prague",
    aliases: ["prague", "praha"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:prague" },
  },
  lisbon: {
    id: "lisbon",
    label: "Lisbon",
    aliases: ["lisbon", "lisboa"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:lisbon" },
  },
  dublin: {
    id: "dublin",
    label: "Dublin",
    aliases: ["dublin", "dublin ireland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:dublin" },
  },
  saoPaulo: {
    id: "saoPaulo",
    label: "Sao Paulo",
    aliases: ["sao paulo", "são paulo", "sao paulo brazil", "são paulo brazil"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:saoPaulo" },
  },
  rioDeJaneiro: {
    id: "rioDeJaneiro",
    label: "Rio de Janeiro",
    aliases: ["rio de janeiro", "rio", "rio de janeiro brazil"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:rioDeJaneiro" },
  },
  brasilia: {
    id: "brasilia",
    label: "Brasilia",
    aliases: ["brasilia", "brasília", "brasilia brazil", "brasília brazil"],
    search: { remote: "businessRegion:amer", onSiteOrHybrid: "city:brasilia" },
  },
  lyon: {
    id: "lyon",
    label: "Lyon",
    aliases: ["lyon", "lyon france", "lyon fr"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:lyon" },
  },
  toulouse: {
    id: "toulouse",
    label: "Toulouse",
    aliases: ["toulouse", "toulouse france", "toulouse fr"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:toulouse" },
  },
  bordeaux: {
    id: "bordeaux",
    label: "Bordeaux",
    aliases: ["bordeaux", "bordeaux france", "bordeaux fr"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:bordeaux" },
  },
  munich: {
    id: "munich",
    label: "Munich",
    aliases: ["munich", "münchen", "munich germany"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:munich" },
  },
  hamburg: {
    id: "hamburg",
    label: "Hamburg",
    aliases: ["hamburg", "hamburg germany"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:hamburg" },
  },
  frankfurt: {
    id: "frankfurt",
    label: "Frankfurt",
    aliases: ["frankfurt", "frankfurt am main", "frankfurt germany"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:frankfurt" },
  },
  cologne: {
    id: "cologne",
    label: "Cologne",
    aliases: ["cologne", "köln", "koln", "cologne germany"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:cologne" },
  },
  manchester: {
    id: "manchester",
    label: "Manchester",
    aliases: ["manchester", "manchester uk", "manchester england"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:manchester" },
  },
  edinburgh: {
    id: "edinburgh",
    label: "Edinburgh",
    aliases: ["edinburgh", "edinburgh uk", "edinburgh scotland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:edinburgh" },
  },
  birminghamUk: {
    id: "birminghamUk",
    label: "Birmingham",
    aliases: ["birmingham uk", "birmingham england", "birmingham united kingdom"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:birminghamUk" },
  },
  turin: {
    id: "turin",
    label: "Turin",
    aliases: ["turin", "torino", "turin italy"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:turin" },
  },
  naples: {
    id: "naples",
    label: "Naples",
    aliases: ["naples", "napoli", "naples italy"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:naples" },
  },
  valencia: {
    id: "valencia",
    label: "Valencia",
    aliases: ["valencia", "valencia spain", "valència"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:valencia" },
  },
  seville: {
    id: "seville",
    label: "Seville",
    aliases: ["seville", "sevilla", "seville spain"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:seville" },
  },
  rotterdam: {
    id: "rotterdam",
    label: "Rotterdam",
    aliases: ["rotterdam", "rotterdam netherlands", "rotterdam nl"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:rotterdam" },
  },
  utrecht: {
    id: "utrecht",
    label: "Utrecht",
    aliases: ["utrecht", "utrecht netherlands", "utrecht nl"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:utrecht" },
  },
  eindhoven: {
    id: "eindhoven",
    label: "Eindhoven",
    aliases: ["eindhoven", "eindhoven netherlands", "eindhoven nl"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:eindhoven" },
  },
  porto: {
    id: "porto",
    label: "Porto",
    aliases: ["porto", "porto portugal"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:porto" },
  },
  braga: {
    id: "braga",
    label: "Braga",
    aliases: ["braga", "braga portugal"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:braga" },
  },
  antwerp: {
    id: "antwerp",
    label: "Antwerp",
    aliases: ["antwerp", "antwerpen", "anvers", "antwerp belgium"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:antwerp" },
  },
  ghent: {
    id: "ghent",
    label: "Ghent",
    aliases: ["ghent", "gent", "ghent belgium"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:ghent" },
  },
  zurich: {
    id: "zurich",
    label: "Zurich",
    aliases: ["zurich", "zürich", "zurich switzerland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:zurich" },
  },
  geneva: {
    id: "geneva",
    label: "Geneva",
    aliases: ["geneva", "genève", "geneva switzerland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:geneva" },
  },
  basel: {
    id: "basel",
    label: "Basel",
    aliases: ["basel", "bâle", "basel switzerland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:basel" },
  },
  lausanne: {
    id: "lausanne",
    label: "Lausanne",
    aliases: ["lausanne", "lausanne switzerland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:lausanne" },
  },
  graz: {
    id: "graz",
    label: "Graz",
    aliases: ["graz", "graz austria"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:graz" },
  },
  linz: {
    id: "linz",
    label: "Linz",
    aliases: ["linz", "linz austria"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:linz" },
  },
  cork: {
    id: "cork",
    label: "Cork",
    aliases: ["cork", "cork ireland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:cork" },
  },
  galway: {
    id: "galway",
    label: "Galway",
    aliases: ["galway", "galway ireland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:galway" },
  },
  stockholm: {
    id: "stockholm",
    label: "Stockholm",
    aliases: ["stockholm", "stockholm sweden"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:stockholm" },
  },
  gothenburg: {
    id: "gothenburg",
    label: "Gothenburg",
    aliases: ["gothenburg", "göteborg", "goteborg", "gothenburg sweden"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:gothenburg" },
  },
  malmo: {
    id: "malmo",
    label: "Malmo",
    aliases: ["malmo", "malmö", "malmo sweden"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:malmo" },
  },
  oslo: {
    id: "oslo",
    label: "Oslo",
    aliases: ["oslo", "oslo norway"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:oslo" },
  },
  bergen: {
    id: "bergen",
    label: "Bergen",
    aliases: ["bergen", "bergen norway"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:bergen" },
  },
  trondheim: {
    id: "trondheim",
    label: "Trondheim",
    aliases: ["trondheim", "trondheim norway"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:trondheim" },
  },
  copenhagen: {
    id: "copenhagen",
    label: "Copenhagen",
    aliases: ["copenhagen", "københavn", "kobenhavn", "copenhagen denmark"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:copenhagen" },
  },
  aarhus: {
    id: "aarhus",
    label: "Aarhus",
    aliases: ["aarhus", "århus", "aarhus denmark"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:aarhus" },
  },
  odense: {
    id: "odense",
    label: "Odense",
    aliases: ["odense", "odense denmark"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:odense" },
  },
  helsinki: {
    id: "helsinki",
    label: "Helsinki",
    aliases: ["helsinki", "helsinki finland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:helsinki" },
  },
  espoo: {
    id: "espoo",
    label: "Espoo",
    aliases: ["espoo", "espoo finland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:espoo" },
  },
  tampere: {
    id: "tampere",
    label: "Tampere",
    aliases: ["tampere", "tampere finland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:tampere" },
  },
  warsaw: {
    id: "warsaw",
    label: "Warsaw",
    aliases: ["warsaw", "warszawa", "warsaw poland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:warsaw" },
  },
  krakow: {
    id: "krakow",
    label: "Krakow",
    aliases: ["krakow", "kraków", "cracow", "krakow poland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:krakow" },
  },
  wroclaw: {
    id: "wroclaw",
    label: "Wroclaw",
    aliases: ["wroclaw", "wrocław", "wroclaw poland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:wroclaw" },
  },
  gdansk: {
    id: "gdansk",
    label: "Gdansk",
    aliases: ["gdansk", "gdańsk", "gdansk poland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:gdansk" },
  },
  brno: {
    id: "brno",
    label: "Brno",
    aliases: ["brno", "brno czech republic", "brno czechia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:brno" },
  },
  ostrava: {
    id: "ostrava",
    label: "Ostrava",
    aliases: ["ostrava", "ostrava czech republic", "ostrava czechia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:ostrava" },
  },
  bucharest: {
    id: "bucharest",
    label: "Bucharest",
    aliases: ["bucharest", "bucuresti", "bucurești", "bucharest romania"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:bucharest" },
  },
  clujNapoca: {
    id: "clujNapoca",
    label: "Cluj-Napoca",
    aliases: ["cluj-napoca", "cluj napoca", "cluj", "cluj romania"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:clujNapoca" },
  },
  timisoara: {
    id: "timisoara",
    label: "Timisoara",
    aliases: ["timisoara", "timișoara", "timisoara romania"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:timisoara" },
  },
  budapest: {
    id: "budapest",
    label: "Budapest",
    aliases: ["budapest", "budapest hungary"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:budapest" },
  },
  debrecen: {
    id: "debrecen",
    label: "Debrecen",
    aliases: ["debrecen", "debrecen hungary"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:debrecen" },
  },
  athens: {
    id: "athens",
    label: "Athens",
    aliases: ["athens", "athens greece", "athina"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:athens" },
  },
  thessaloniki: {
    id: "thessaloniki",
    label: "Thessaloniki",
    aliases: ["thessaloniki", "salonica", "thessaloniki greece"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:thessaloniki" },
  },
  kyiv: {
    id: "kyiv",
    label: "Kyiv",
    aliases: ["kyiv", "kiev", "kyiv ukraine"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:kyiv" },
  },
  lviv: {
    id: "lviv",
    label: "Lviv",
    aliases: ["lviv", "l'viv", "lviv ukraine"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:lviv" },
  },
  odesa: {
    id: "odesa",
    label: "Odesa",
    aliases: ["odesa", "odessa", "odesa ukraine"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:odesa" },
  },
  zagreb: {
    id: "zagreb",
    label: "Zagreb",
    aliases: ["zagreb", "zagreb croatia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:zagreb" },
  },
  split: {
    id: "split",
    label: "Split",
    aliases: ["split", "split croatia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:split" },
  },
  bratislava: {
    id: "bratislava",
    label: "Bratislava",
    aliases: ["bratislava", "bratislava slovakia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:bratislava" },
  },
  kosice: {
    id: "kosice",
    label: "Kosice",
    aliases: ["kosice", "košice", "kosice slovakia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:kosice" },
  },
  ljubljana: {
    id: "ljubljana",
    label: "Ljubljana",
    aliases: ["ljubljana", "ljubljana slovenia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:ljubljana" },
  },
  maribor: {
    id: "maribor",
    label: "Maribor",
    aliases: ["maribor", "maribor slovenia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:maribor" },
  },
  sofia: {
    id: "sofia",
    label: "Sofia",
    aliases: ["sofia", "sofia bulgaria"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:sofia" },
  },
  plovdiv: {
    id: "plovdiv",
    label: "Plovdiv",
    aliases: ["plovdiv", "plovdiv bulgaria"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:plovdiv" },
  },
  vilnius: {
    id: "vilnius",
    label: "Vilnius",
    aliases: ["vilnius", "vilnius lithuania"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:vilnius" },
  },
  kaunas: {
    id: "kaunas",
    label: "Kaunas",
    aliases: ["kaunas", "kaunas lithuania"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:kaunas" },
  },
  riga: {
    id: "riga",
    label: "Riga",
    aliases: ["riga", "rīga", "riga latvia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:riga" },
  },
  daugavpils: {
    id: "daugavpils",
    label: "Daugavpils",
    aliases: ["daugavpils", "daugavpils latvia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:daugavpils" },
  },
  tallinn: {
    id: "tallinn",
    label: "Tallinn",
    aliases: ["tallinn", "tallinn estonia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:tallinn" },
  },
  tartu: {
    id: "tartu",
    label: "Tartu",
    aliases: ["tartu", "tartu estonia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:tartu" },
  },
  luxembourgCity: {
    id: "luxembourgCity",
    label: "Luxembourg City",
    aliases: ["luxembourg city", "luxembourg ville", "luxembourg luxembourg"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:luxembourgCity" },
  },
  reykjavik: {
    id: "reykjavik",
    label: "Reykjavik",
    aliases: ["reykjavik", "reykjavík", "reykjavik iceland"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:reykjavik" },
  },
  belgrade: {
    id: "belgrade",
    label: "Belgrade",
    aliases: ["belgrade", "beograd", "belgrade serbia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:belgrade" },
  },
  noviSad: {
    id: "noviSad",
    label: "Novi Sad",
    aliases: ["novi sad", "novi sad serbia"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:noviSad" },
  },
  valletta: {
    id: "valletta",
    label: "Valletta",
    aliases: ["valletta", "valletta malta"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:valletta" },
  },
  sliema: {
    id: "sliema",
    label: "Sliema",
    aliases: ["sliema", "sliema malta"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:sliema" },
  },
  nicosia: {
    id: "nicosia",
    label: "Nicosia",
    aliases: ["nicosia", "lefkosia", "nicosia cyprus"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:nicosia" },
  },
  limassol: {
    id: "limassol",
    label: "Limassol",
    aliases: ["limassol", "lemesos", "limassol cyprus"],
    search: { remote: "businessRegion:emea", onSiteOrHybrid: "city:limassol" },
  },
} as const;

export const LOCATIONS_MAP = {
  ...WORLDWIDE_LOCATIONS_MAP,
  ...BUSINESS_REGIONS_MAP,
  ...CONTINENTS_MAP,
  ...COUNTRIES_MAP,
  ...CITIES_MAP,
} as const;

export const SKILLS_MAP = {
  agGrid: {
    id: "ag-grid",
    label: "AG Grid",
    aliases: ["ag-grid", "ag grid", "aggrid", "ag-grid-react"],
  },
  ahrefs: {
    id: "ahrefs",
    label: "Ahrefs",
    aliases: ["ahrefs", "ahrefs seo tool", "backlink checker ahrefs", "keyword explorer ahrefs", "seo suite ahrefs"],
  },
  airflow: {
    id: "airflow",
    label: "Airflow",
    aliases: ["airflow", "apache airflow", "workflow orchestration airflow", "dag scheduler airflow"],
  },
  android: {
    id: "android",
    label: "Android",
    aliases: ["android"],
  },
  angular: {
    id: "angular",
    label: "Angular",
    aliases: ["angular", "angularjs", "angular.js"],
  },
  ansible: {
    id: "ansible",
    label: "Ansible",
    aliases: ["ansible", "ansible automation", "ansible playbook", "redhat ansible"],
  },
  apache: {
    id: "apache",
    label: "Apache",
    aliases: ["apache", "apache http server", "apache web server", "httpd", "apache2"],
  },
  apollo: {
    id: "apollo",
    label: "Apollo",
    aliases: ["apollo", "apollo graphql", "apollo client", "apollo server", "apollo federation"],
  },
  aspnet: {
    id: "aspnet",
    label: "ASP.NET",
    aliases: ["asp.net", "asp.net core", "asp.net mvc", "asp.net web api"],
  },
  assembly: {
    id: "assembly",
    label: "Assembly",
    aliases: ["assembly", "asm", "assembly language", "low-level assembly"],
  },
  astro: {
    id: "astro",
    label: "Astro",
    aliases: ["astro"],
  },
  aws: {
    id: "aws",
    label: "AWS",
    aliases: ["amazon web services", "aws cloud", "ec2 s3 aws", "aws platform", "aws"],
  },
  azure: {
    id: "azure",
    label: "Azure",
    aliases: ["azure", "microsoft azure", "azure cloud", "azure platform", "ms azure"],
  },
  babel: {
    id: "babel",
    label: "Babel",
    aliases: ["babel", "babeljs", "babel.js"],
  },
  backbone: {
    id: "backbone",
    label: "Backbone.js",
    aliases: ["backbone", "backbonejs", "backbone.js"],
  },
  bash: {
    id: "bash",
    label: "Bash",
    aliases: ["bash", "shell", "sh", "bash shell", "gnu bash", "scripting shell"],
  },
  bigQuery: {
    id: "bigQuery",
    label: "BigQuery",
    aliases: ["bigquery", "google bigquery", "gcp bigquery", "big query", "data warehouse bigquery"],
  },
  bootstrap: {
    id: "bootstrap",
    label: "Bootstrap",
    aliases: ["bootstrap", "bootstrapcss", "twitter bootstrap"],
  },
  cassandra: {
    id: "cassandra",
    label: "Cassandra",
    aliases: ["cassandra", "apache cassandra", "nosql cassandra", "wide column cassandra"],
  },
  chai: {
    id: "chai",
    label: "Chai",
    aliases: ["chai", "chai.js", "chai assertion library", "node chai", "javascript chai"],
  },
  chef: {
    id: "chef",
    label: "Chef",
    aliases: ["chef", "chef infra", "chef automation", "infrastructure chef"],
  },
  clojure: {
    id: "clojure",
    label: "Clojure",
    aliases: ["clojure", "clj", "clojure language", "jvm clojure"],
  },
  cloud: {
    id: "cloud",
    label: "Cloud",
    aliases: ["cloud", "cloud computing", "iaas paas saas", "aws azure gcp", "cloud infrastructure"],
  },
  consul: {
    id: "consul",
    label: "Consul",
    aliases: ["consul", "hashicorp consul", "service discovery consul", "consul kv"],
  },
  contentSeo: {
    id: "contentSeo",
    label: "Content SEO",
    aliases: ["content seo", "seo content writing", "content optimization", "blog seo", "semantic seo"],
  },
  coreWebVitals: {
    id: "coreWebVitals",
    label: "Core Web Vitals",
    aliases: ["core web vitals", "lcp fid cls", "page speed metrics", "google page experience", "web vitals seo"],
  },
  cpp: {
    id: "cpp",
    label: "C++",
    aliases: ["c++", "cpp", "c plus plus", "cplusplus"],
  },
  csharp: {
    id: "csharp",
    label: "C#",
    aliases: ["c#", "c sharp", "dotnet", ".net", "csharp dotnet"],
  },
  css: {
    id: "css",
    label: "CSS",
    aliases: ["css", "css3"],
  },
  cybersecurity: {
    id: "cybersecurity",
    label: "Cybersecurity",
    aliases: ["cybersecurity", "information security", "infosec", "cyber security", "security engineering"],
  },
  cypress: {
    id: "cypress",
    label: "Cypress",
    aliases: [
      "cypress.io",
      "cypress testing",
      "e2e cypress",
      "frontend testing cypress",
      "cypress",
      "cypressio",
      "cypress.io",
    ],
  },
  d3: {
    id: "d3",
    label: "D3.js",
    aliases: ["d3", "d3js", "d3.js", "data-driven documents"],
  },
  dagger: {
    id: "dagger",
    label: "Dagger",
    aliases: [
      "dagger",
      "dagger ci",
      "dagger ci/cd",
      "dagger pipeline",
      "dagger dependency injection",
      "dagger android",
      "dagger hilt",
    ],
  },
  dart: {
    id: "dart",
    label: "Dart",
    aliases: ["dart", "dartlang", "flutter dart", "dart sdk"],
  },
  delphi: {
    id: "delphi",
    label: "Delphi",
    aliases: ["delphi", "object pascal", "pascal", "embarcadero delphi"],
  },
  distributedsystem: {
    id: "distributedsystem",
    label: "Distributed System",
    aliases: ["distributed system", "distributed systems", "distributed computing", "distributed architecture"],
  },
  django: {
    id: "django",
    label: "Django",
    aliases: ["django", "django framework", "django python", "django orm"],
  },
  dns: {
    id: "dns",
    label: "DNS",
    aliases: ["dns", "domain name system", "dns records", "name resolution dns", "bind dns"],
  },
  docker: {
    id: "docker",
    label: "Docker",
    aliases: ["docker container", "containerization docker", "docker engine", "docker"],
  },
  dotnet: {
    id: "dotnet",
    label: ".NET",
    aliases: [".net", "dot net", ".net framework", ".net core", ".net platform"],
  },
  dynamoDB: {
    id: "dynamoDB",
    label: "DynamoDB",
    aliases: ["dynamodb", "aws dynamodb", "amazon dynamodb", "dynamodb nosql"],
  },
  ec2: {
    id: "ec2",
    label: "EC2",
    aliases: ["ec2", "aws ec2", "cloud instances ec2"],
  },
  elasticsearch: {
    id: "elasticsearch",
    label: "Elasticsearch",
    aliases: ["elasticsearch", "elastic search", "elk elasticsearch", "search engine elastic"],
  },
  electron: {
    id: "electron",
    label: "Electron",
    aliases: ["electron", "electronjs", "electron.js", "desktop electron", "chromium node"],
  },
  elixir: {
    id: "elixir",
    label: "Elixir",
    aliases: ["elixir", "mix", "phoenix", "elixir lang", "erlang vm elixir"],
  },
  ember: {
    id: "ember",
    label: "Ember.js",
    aliases: ["ember", "emberjs", "ember.js"],
  },
  entityFramework: {
    id: "entityFramework",
    label: "Entity Framework",
    aliases: ["entity framework", "ef", "ef core", "entity framework core", "microsoft ef"],
  },
  erlang: {
    id: "erlang",
    label: "Erlang",
    aliases: ["erlang", "otp", "erlang otp", "beam language"],
  },
  erp: {
    id: "erp",
    label: "ERP",
    aliases: ["erp", "enterprise resource planning", "erp systems", "business management software"],
  },
  eslint: {
    id: "eslint",
    label: "ESLint",
    aliases: ["eslint"],
  },
  etl: {
    id: "etl",
    label: "ETL",
    aliases: ["etl", "extract transform load", "data pipeline", "etl pipeline", "data integration"],
  },
  ffmpeg: {
    id: "ffmpeg",
    label: "FFmpeg",
    aliases: ["ffmpeg", "ffmpeg cli", "libav", "video encoding ffmpeg", "media toolkit"],
  },
  firebase: {
    id: "firebase",
    label: "Firebase",
    aliases: ["firebase", "google firebase", "firebase backend", "firebase platform"],
  },
  firewalls: {
    id: "firewalls",
    label: "Firewalls",
    aliases: ["firewalls", "network firewall", "security firewall", "waf", "iptables firewall"],
  },
  flask: {
    id: "flask",
    label: "Flask",
    aliases: ["flask", "flask python", "microframework flask", "python flask"],
  },
  flutter: {
    id: "flutter",
    label: "Flutter",
    aliases: ["flutter"],
  },
  formik: {
    id: "formik",
    label: "Formik",
    aliases: ["formik"],
  },
  gatsby: {
    id: "gatsby",
    label: "Gatsby",
    aliases: ["gatsby", "gatsbyjs", "gatsby.js"],
  },
  gcp: {
    id: "gcp",
    label: "Google Cloud Platform",
    aliases: ["google cloud platform", "google cloud", "gcp cloud", "google cloud platform gcp"],
  },
  go: {
    id: "go",
    label: "Go",
    aliases: ["go", "golang", "go lang", "google go"],
  },
  googleanalytics: {
    id: "googleanalytics",
    label: "Google Analytics",
    aliases: ["google analytics", "ga", "google analytics 4", "ga4", "analytics tracking", "web analytics google"],
  },
  googlesearchconsole: {
    id: "googlesearchconsole",
    label: "Google Search Console",
    aliases: ["google search console", "gsc", "search console", "google webmaster tools", "index coverage tool"],
  },
  grafana: {
    id: "grafana",
    label: "Grafana",
    aliases: ["grafana", "grafana labs", "metrics dashboard grafana", "observability grafana"],
  },
  graphql: {
    id: "graphql",
    label: "GraphQL",
    aliases: ["graphql", "graph ql", "graphql api", "graphql schema", "gql"],
  },
  groovy: {
    id: "groovy",
    label: "Groovy",
    aliases: ["groovy", "apache groovy", "gradle groovy", "grails groovy"],
  },
  grpc: {
    id: "grpc",
    label: "GRPC",
    aliases: ["grpc", "grpc protocol", "google rpc", "remote procedure call grpc"],
  },
  guidewire: {
    id: "guidewire",
    label: "Guidewire",
    aliases: ["guidewire", "guidewire software", "insurance suite guidewire", "policycenter guidewire"],
  },
  hadoop: {
    id: "hadoop",
    label: "Hadoop",
    aliases: ["hadoop", "apache hadoop", "hadoop ecosystem", "hadoop framework", "big data hadoop"],
  },
  haproxy: {
    id: "haproxy",
    label: "HAProxy",
    aliases: ["haproxy", "load balancer haproxy", "reverse proxy haproxy", "high availability proxy"],
  },
  haskell: {
    id: "haskell",
    label: "Haskell",
    aliases: ["haskell", "ghc", "cabal", "stack", "haskell lang"],
  },
  hbase: {
    id: "hbase",
    label: "HBase",
    aliases: ["hbase", "apache hbase", "hadoop hbase", "wide column hbase"],
  },
  hdfs: {
    id: "hdfs",
    label: "HDFS",
    aliases: ["hdfs", "hadoop distributed file system", "hadoop fs", "distributed file system hdfs"],
  },
  heroku: {
    id: "heroku",
    label: "Heroku",
    aliases: ["heroku", "heroku platform", "paas heroku", "salesforce heroku"],
  },
  hibernate: {
    id: "hibernate",
    label: "Hibernate",
    aliases: ["hibernate", "hibernate orm", "jpa hibernate", "java hibernate"],
  },
  html: {
    id: "html",
    label: "HTML",
    aliases: ["html", "html5"],
  },
  informatica: {
    id: "informatica",
    label: "Informatica",
    aliases: [
      "informatica",
      "informatica powercenter",
      "informatica etl",
      "informatica iics",
      "data integration informatica",
    ],
  },
  ionic: {
    id: "ionic",
    label: "Ionic",
    aliases: ["ionic", "@ionic/react", "@ionic/angular"],
  },
  ios: {
    id: "ios",
    label: "iOS",
    aliases: ["ios"],
  },
  itsm: {
    id: "itsm",
    label: "ITSM",
    aliases: ["itsm", "it service management", "information technology service management", "itsm processes"],
  },
  java: {
    id: "java",
    label: "Java",
    aliases: ["java", "jdk", "jre", "jvm", "java se", "java ee", "spring java"],
  },
  javascript: {
    id: "javascript",
    label: "JavaScript",
    aliases: ["javascript", "js", "ecmascript"],
  },
  jenkins: {
    id: "jenkins",
    label: "Jenkins",
    aliases: ["jenkins", "ci jenkins", "jenkins pipeline", "automation server jenkins"],
  },
  jest: {
    id: "jest",
    label: "Jest",
    aliases: ["jestjs", "jest testing", "javascript jest", "react testing jest", "jest"],
  },
  jmeter: {
    id: "jmeter",
    label: "JMeter",
    aliases: ["jmeter", "apache jmeter", "performance testing jmeter", "load testing jmeter"],
  },
  joomla: {
    id: "joomla",
    label: "Joomla",
    aliases: ["joomla", "joomla cms", "joomla framework", "content management joomla"],
  },
  jquery: {
    id: "jquery",
    label: "jQuery",
    aliases: ["jquery", "jquery.js"],
  },
  junit: {
    id: "junit",
    label: "JUnit",
    aliases: ["junit", "java junit", "junit 4", "junit 5", "unit testing java junit"],
  },
  jwt: {
    id: "jwt",
    label: "JWT",
    aliases: ["jwt", "json web token", "jwt auth", "token based authentication", "bearer token jwt"],
  },
  kafka: {
    id: "kafka",
    label: "Kafka",
    aliases: ["kafka", "apache kafka", "event streaming kafka", "message broker kafka", "kafka streams"],
  },
  keras: {
    id: "keras",
    label: "Keras",
    aliases: ["keras", "tensorflow keras", "deep learning keras", "keras api", "neural network keras"],
  },
  keywordResearch: {
    id: "keywordResearch",
    label: "Keyword Research",
    aliases: ["keyword research", "seo keywords", "keyword analysis", "search intent research", "keyword planning"],
  },
  kotlin: {
    id: "kotlin",
    label: "Kotlin",
    aliases: ["kotlin", "kotlin jvm", "android kotlin", "jetbrains kotlin"],
  },
  kubernetes: {
    id: "kubernetes",
    label: "Kubernetes",
    aliases: ["k8s", "kube", "container orchestration kubernetes", "kubernetes"],
  },
  laravel: {
    id: "laravel",
    label: "Laravel",
    aliases: ["laravel", "laravel php", "laravel framework", "php laravel"],
  },
  linux: {
    id: "linux",
    label: "Linux",
    aliases: ["linux", "linux os", "ubuntu linux", "debian linux", "unix-like operating system"],
  },
  localSeo: {
    id: "localSeo",
    label: "Local SEO",
    aliases: [
      "local seo",
      "google business profile",
      "local search optimization",
      "map pack seo",
      "local listings optimization",
    ],
  },
  logstash: {
    id: "logstash",
    label: "Logstash",
    aliases: ["logstash", "elastic logstash", "elk logstash", "log ingestion logstash"],
  },
  lua: {
    id: "lua",
    label: "Lua",
    aliases: ["lua", "lua 5", "luajit", "lua scripting"],
  },
  macOS: {
    id: "macOS",
    label: "macOS",
    aliases: ["macos", "apple macos", "osx", "mac os", "darwin operating system"],
  },
  magento: {
    id: "magento",
    label: "Magento",
    aliases: ["magento", "adobe commerce", "magento ecommerce", "magento 2"],
  },
  mariaDB: {
    id: "mariaDB",
    label: "MariaDB",
    aliases: ["mariadb", "mariadb sql", "mysql fork mariadb", "maria db"],
  },
  materialUi: {
    id: "material-ui",
    label: "Material UI",
    aliases: ["material-ui", "material ui", "mui", "@mui/material"],
  },
  maven: {
    id: "maven",
    label: "Maven",
    aliases: ["maven", "apache maven", "maven build tool", "pom.xml maven"],
  },
  microservices: {
    id: "microservices",
    label: "Microservices",
    aliases: ["microservices", "microservice architecture", "distributed microservices", "microservices architecture"],
  },
  mobx: {
    id: "mobx",
    label: "MobX",
    aliases: ["mobx"],
  },
  mocha: {
    id: "mocha",
    label: "Mocha",
    aliases: ["mocha", "mochajs", "mocha testing framework", "node mocha", "javascript mocha"],
  },
  mockito: {
    id: "mockito",
    label: "Mockito",
    aliases: ["mockito", "java mockito", "mocking framework mockito", "unit testing mockito"],
  },
  mongodb: {
    id: "mongodb",
    label: "MongoDB",
    aliases: ["mongodb", "mongo db", "nosql mongodb", "mongodb atlas"],
  },
  moz: {
    id: "moz",
    label: "Moz",
    aliases: ["moz", "moz pro", "moz seo tool", "domain authority moz", "keyword explorer moz"],
  },
  msSqlServer: {
    id: "msSqlServer",
    label: "MS SQL Server",
    aliases: ["ms sql server", "mssql", "sql server", "microsoft sql server", "tsql"],
  },
  mysql: {
    id: "mysql",
    label: "MySQL",
    aliases: ["mysql", "mysql database", "maria/mysql", "mysql 8", "sql mysql"],
  },
  neo4j: {
    id: "neo4j",
    label: "Neo4j",
    aliases: ["neo4j", "graph database neo4j", "cypher neo4j", "graph db neo4j"],
  },
  nextjs: {
    id: "nextjs",
    label: "Next.js",
    aliases: ["next", "nextjs", "next.js"],
  },
  nfs: {
    id: "nfs",
    label: "NFS",
    aliases: ["nfs", "network file system", "nfs protocol", "linux nfs"],
  },
  nginx: {
    id: "nginx",
    label: "Nginx",
    aliases: ["nginx", "nginx web server", "reverse proxy nginx", "load balancer nginx", "engine x"],
  },
  nodejs: {
    id: "nodejs",
    label: "Node.js",
    aliases: ["node.js", "node", "node js", "node.js runtime", "nodejs runtime"],
  },
  nosql: {
    id: "nosql",
    label: "NoSQL",
    aliases: ["nosql", "nosql database", "non relational database", "document database", "key value store"],
  },
  npm: {
    id: "npm",
    label: "npm",
    aliases: ["npm", "node package manager"],
  },
  numpy: {
    id: "numpy",
    label: "NumPy",
    aliases: ["numpy", "numpy python", "np", "numerical python numpy", "array computing numpy"],
  },
  nuxt: {
    id: "nuxt",
    label: "Nuxt",
    aliases: ["nuxt", "nuxtjs", "nuxt.js"],
  },
  objectiveC: {
    id: "objectiveC",
    label: "Objective-C",
    aliases: ["objective-c", "objective c", "objc", "ios objective-c", "apple objective-c"],
  },
  offPageSeo: {
    id: "offPageSeo",
    label: "Off-Page SEO",
    aliases: ["off-page seo", "offpage seo", "link building", "backlink strategy", "domain authority building"],
  },
  onPageSeo: {
    id: "onPageSeo",
    label: "On-Page SEO",
    aliases: [
      "on-page seo",
      "onpage seo",
      "content optimization seo",
      "meta tags optimization",
      "internal linking seo",
    ],
  },
  openShift: {
    id: "openShift",
    label: "OpenShift",
    aliases: ["openshift", "red hat openshift", "ocp", "kubernetes openshift"],
  },
  openSource: {
    id: "openSource",
    label: "Open Source",
    aliases: ["open source", "open-source software", "oss", "foss", "public source code"],
  },
  openStack: {
    id: "openStack",
    label: "OpenStack",
    aliases: ["openstack", "open stack", "iaas openstack", "private cloud openstack"],
  },
  oracle: {
    id: "oracle",
    label: "Oracle",
    aliases: ["oracle", "oracle database", "oracle db", "oracle rdbms", "oracle sql"],
  },
  oracleErp: {
    id: "oracleErp",
    label: "Oracle ERP",
    aliases: ["oracle erp", "oracle enterprise resource planning", "oracle fusion erp", "oracle financials"],
  },
  packer: {
    id: "packer",
    label: "Packer",
    aliases: ["packer", "hashicorp packer", "image builder packer"],
  },
  pandas: {
    id: "pandas",
    label: "Pandas",
    aliases: ["pandas", "pandas python", "dataframe pandas", "pd", "data analysis pandas"],
  },
  perl: {
    id: "perl",
    label: "Perl",
    aliases: ["perl", "perl 5", "cpan", "perl scripting"],
  },
  php: {
    id: "php",
    label: "PHP",
    aliases: ["php", "php8", "laravel", "symfony", "hypertext preprocessor"],
  },
  playwright: {
    id: "playwright",
    label: "Playwright",
    aliases: ["playwright"],
  },
  pnpm: {
    id: "pnpm",
    label: "pnpm",
    aliases: ["pnpm"],
  },
  postcss: {
    id: "postcss",
    label: "PostCSS",
    aliases: ["postcss"],
  },
  postgis: {
    id: "postgis",
    label: "PostGIS",
    aliases: ["postgis", "postgres gis", "geospatial postgres", "spatial database postgis"],
  },
  postgresql: {
    id: "postgresql",
    label: "PostgreSQL",
    aliases: ["postgresql", "postgres", "psql", "postgres db", "postgis base"],
  },
  prettier: {
    id: "prettier",
    label: "Prettier",
    aliases: ["prettier"],
  },
  pubsub: {
    id: "pubsub",
    label: "Pub/Sub",
    aliases: ["pub/sub", "google pubsub", "cloud pub/sub", "message pubsub", "event pubsub"],
  },
  pulsar: {
    id: "pulsar",
    label: "Pulsar",
    aliases: ["pulsar", "apache pulsar", "message broker pulsar", "event streaming pulsar"],
  },
  puppet: {
    id: "puppet",
    label: "Puppet",
    aliases: ["puppet", "puppet labs", "puppet automation", "config management puppet"],
  },
  puppeteer: {
    id: "puppeteer",
    label: "Puppeteer",
    aliases: [
      "puppeteer",
      "puppeteer js",
      "headless chrome puppeteer",
      "node puppeteer",
      "browser automation puppeteer",
    ],
  },
  pyspark: {
    id: "pyspark",
    label: "PySpark",
    aliases: ["pyspark", "spark python", "apache spark python", "pyspark sql", "spark dataframe python"],
  },
  python: {
    id: "python",
    label: "Python",
    aliases: ["python", "py", "cpython", "pip", "pypi"],
  },
  pytorch: {
    id: "pytorch",
    label: "PyTorch",
    aliases: ["pytorch", "torch", "facebook pytorch", "deep learning pytorch", "torch library"],
  },
  rabbitmq: {
    id: "rabbitmq",
    label: "RabbitMQ",
    aliases: ["rabbitmq", "rabbit mq", "message broker rabbitmq", "amqp rabbitmq"],
  },
  rdbms: {
    id: "rdbms",
    label: "RDBMS",
    aliases: ["rdbms", "relational database", "relational database management system", "sql database"],
  },
  react: {
    id: "react",
    label: "React",
    aliases: ["react", "reactjs", "react.js"],
  },
  reactContext: {
    id: "react-context",
    label: "React Context",
    aliases: ["react context", "react context api", "context api", "react-context"],
  },
  reactHookForm: {
    id: "react-hook-form",
    label: "React Hook Form",
    aliases: ["react hook form", "react-hook-form", "reacthookform"],
  },
  reactNative: {
    id: "react-native",
    label: "React Native",
    aliases: ["react native", "react-native", "reactnative"],
  },
  reactProfiler: {
    id: "react-profiler",
    label: "React Profiler",
    aliases: ["react profiler", "react-profiler", "react devtools profiler"],
  },
  reactQuery: {
    id: "react-query",
    label: "React Query",
    aliases: ["react query", "react-query", "tanstack query"],
  },
  reactTestingLibrary: {
    id: "react-testing-library",
    label: "React Testing Library",
    aliases: ["react testing library", "rtl", "react-testing-library"],
  },
  realm: {
    id: "realm",
    label: "Realm",
    aliases: ["realm", "realm db", "realm database", "mongodb realm", "realm mobile database"],
  },
  redis: {
    id: "redis",
    label: "Redis",
    aliases: ["redis", "redis cache", "redis db", "in memory redis", "redis store"],
  },
  redux: {
    id: "redux",
    label: "Redux",
    aliases: ["redux", "reduxjs", "redux.js", "redux toolkit", "redux saga", "redux thunk"],
  },
  remix: {
    id: "remix",
    label: "Remix",
    aliases: ["remix", "remix.run"],
  },
  remoteSensing: {
    id: "remoteSensing",
    label: "Remote Sensing",
    aliases: ["remote sensing", "earth observation", "satellite imaging", "gis remote sensing", "geospatial analysis"],
  },
  roku: {
    id: "roku",
    label: "Roku",
    aliases: ["roku", "roku sdk", "roku channel development", "brightscript roku"],
  },
  rollup: {
    id: "rollup",
    label: "Rollup",
    aliases: ["rollup", "rollup.js"],
  },
  rpa: {
    id: "rpa",
    label: "RPA",
    aliases: ["rpa", "robotic process automation", "ui automation bots", "process automation rpa"],
  },
  rspec: {
    id: "rspec",
    label: "RSpec",
    aliases: ["rspec", "ruby rspec", "rspec testing", "behavior driven development rspec", "bdd rspec"],
  },
  rtos: {
    id: "rtos",
    label: "RTOS",
    aliases: ["rtos", "real time operating system", "embedded rtos", "freertos", "deterministic os"],
  },
  ruby: {
    id: "ruby",
    label: "Ruby",
    aliases: ["ruby", "ruby lang", "rails", "ruby on rails", "bundler"],
  },
  rubyOnRails: {
    id: "rubyOnRails",
    label: "Ruby on Rails",
    aliases: ["ruby on rails", "rails", "ror", "ruby rails", "rails framework"],
  },
  rust: {
    id: "rust",
    label: "Rust",
    aliases: ["rust", "rustlang", "cargo", "rustc", "rust programming language"],
  },
  rxjs: {
    id: "rxjs",
    label: "RxJS",
    aliases: ["rxjs", "reactive extensions for javascript"],
  },
  saltStack: {
    id: "saltStack",
    label: "SaltStack",
    aliases: ["saltstack", "salt", "saltstack automation", "salt config management"],
  },
  sass: {
    id: "sass",
    label: "Sass",
    aliases: ["sass", "scss"],
  },
  scala: {
    id: "scala",
    label: "Scala",
    aliases: ["scala", "scala lang", "sbt", "scala jvm"],
  },
  schemaMarkup: {
    id: "schemaMarkup",
    label: "Schema Markup",
    aliases: ["schema markup", "structured data", "json ld", "rich snippets", "schema.org markup"],
  },
  scikitLearn: {
    id: "scikitLearn",
    label: "Scikit-learn",
    aliases: ["scikit-learn", "sklearn", "scikit learn", "python sklearn", "machine learning sklearn"],
  },
  screamingFrog: {
    id: "screamingFrog",
    label: "Screaming Frog",
    aliases: ["screaming frog", "screaming frog seo spider", "seo crawler screaming frog", "site audit screaming frog"],
  },
  sdlc: {
    id: "sdlc",
    label: "SDLC",
    aliases: ["sdlc", "software development lifecycle", "software development life cycle", "application lifecycle"],
  },
  selenium: {
    id: "selenium",
    label: "Selenium",
    aliases: ["selenium webdriver", "browser automation selenium", "e2e selenium", "selenium testing", "selenium"],
  },
  semrush: {
    id: "semrush",
    label: "SEMrush",
    aliases: [
      "semrush",
      "semrush seo",
      "keyword research semrush",
      "seo toolkit semrush",
      "competitive analysis semrush",
    ],
  },
  serviceNow: {
    id: "serviceNow",
    label: "ServiceNow",
    aliases: ["servicenow", "servicenow platform", "itsm servicenow", "sn platform"],
  },
  sfdc: {
    id: "sfdc",
    label: "SFDC",
    aliases: ["sfdc", "salesforce", "salesforce crm", "force.com", "salesforce platform"],
  },
  sitecore: {
    id: "sitecore",
    label: "Sitecore",
    aliases: ["sitecore", "sitecore cms", "sitecore xp", "sitecore experience platform"],
  },
  smtp: {
    id: "smtp",
    label: "SMTP",
    aliases: ["smtp", "simple mail transfer protocol", "email smtp", "mail protocol smtp"],
  },
  soap: {
    id: "soap",
    label: "SOAP",
    aliases: ["soap", "simple object access protocol", "soap web services", "xml soap api"],
  },
  solidity: {
    id: "solidity",
    label: "Solidity",
    aliases: ["solidity", "ethereum solidity", "evm", "smart contracts", "solidity lang"],
  },
  spark: {
    id: "spark",
    label: "Spark",
    aliases: ["spark", "apache spark", "spark ml", "spark sql", "big data spark"],
  },
  spinnaker: {
    id: "spinnaker",
    label: "Spinnaker",
    aliases: ["spinnaker", "continuous delivery spinnaker", "cd spinnaker", "netflix spinnaker"],
  },
  splunk: {
    id: "splunk",
    label: "Splunk",
    aliases: ["splunk", "splunk enterprise", "log analytics splunk", "siem splunk"],
  },
  spring: {
    id: "spring",
    label: "Spring",
    aliases: ["spring", "spring ecosystem", "spring framework ecosystem"],
  },
  springBoot: {
    id: "springBoot",
    label: "Spring Boot",
    aliases: ["spring boot", "springboot", "spring boot framework"],
  },
  springFramework: {
    id: "springFramework",
    label: "Spring Framework",
    aliases: ["spring core", "spring framework", "spring mvc"],
  },
  sqlite: {
    id: "sqlite",
    label: "SQLite",
    aliases: ["sqlite", "sqlite3", "embedded sqlite", "file database sqlite"],
  },
  storybook: {
    id: "storybook",
    label: "Storybook",
    aliases: ["storybook", "@storybook/react"],
  },
  styledComponents: {
    id: "styled-components",
    label: "Styled Components",
    aliases: ["styled-components", "styled components", "styledcomponents"],
  },
  subversion: {
    id: "subversion",
    label: "Subversion",
    aliases: ["subversion", "svn", "apache svn", "version control subversion"],
  },
  svelte: {
    id: "svelte",
    label: "Svelte",
    aliases: ["svelte"],
  },
  sveltekit: {
    id: "sveltekit",
    label: "SvelteKit",
    aliases: ["sveltekit", "svelte-kit"],
  },
  swift: {
    id: "swift",
    label: "Swift",
    aliases: ["swift", "swift lang", "ios swift", "swiftui", "xcode swift"],
  },
  swiftui: {
    id: "swiftui",
    label: "SwiftUI",
    aliases: ["swiftui", "swift ui"],
  },
  tableau: {
    id: "tableau",
    label: "Tableau",
    aliases: ["tableau", "tableau software", "data visualization tableau", "tableau desktop"],
  },
  tailwind: {
    id: "tailwindcss",
    label: "Tailwind CSS",
    aliases: ["tailwind", "tailwindcss", "tailwind css"],
  },
  tcpIp: {
    id: "tcpIp",
    label: "TCP/IP",
    aliases: ["tcp/ip", "tcp ip stack", "tcp/ip protocol suite", "networking tcp ip", "internet protocol suite"],
  },
  technicalSeo: {
    id: "technicalSeo",
    label: "Technical SEO",
    aliases: [
      "technical seo",
      "site crawl optimization",
      "seo audit",
      "core web vitals seo",
      "indexability optimization",
    ],
  },
  tempo: {
    id: "tempo",
    label: "Tempo",
    aliases: ["tempo", "grafana tempo", "tempo tracing", "distributed tracing tempo"],
  },
  memcached: {
    id: "memcached",
    label: "Memcached",
    aliases: ["memcached", "memcache"],
  },
  sql: {
    id: "sql",
    label: "SQL",
    aliases: ["sql", "structured query language"],
  },
  nats: {
    id: "nats",
    label: "NATS",
    aliases: ["nats", "nats.io"],
  },
  asyncio: {
    id: "asyncio",
    label: "AsyncIO",
    aliases: ["asyncio", "async io"],
  },
  loki: {
    id: "loki",
    label: "Grafana Loki",
    aliases: ["loki", "grafana loki"],
  },
  mimir: {
    id: "mimir",
    label: "Grafana Mimir",
    aliases: ["mimir", "grafana mimir"],
  },
  ci_cd: {
    id: "ci_cd",
    label: "CI/CD",
    aliases: ["ci/cd", "continuous integration"],
  },
  contentful: {
    id: "contentful",
    label: "Contentful",
    aliases: ["contentful", "headless cms"],
  },
  vercel: {
    id: "vercel",
    label: "Vercel",
    aliases: ["vercel", "vercel deployment"],
  },
  segment: {
    id: "segment",
    label: "Segment",
    aliases: ["segment", "twilio segment"],
  },
  optimizely: {
    id: "optimizely",
    label: "Optimizely",
    aliases: ["optimizely", "ab testing"],
  },
  vwo: {
    id: "vwo",
    label: "VWO",
    aliases: ["vwo", "visual website optimizer"],
  },
  temporal: {
    id: "temporal",
    label: "Temporal",
    aliases: ["temporal", "temporal io", "temporal workflow", "temporal cadence", "temporal server"],
  },
  tensorflow: {
    id: "tensorflow",
    label: "TensorFlow",
    aliases: ["tensorflow", "tf", "tensorflow keras", "google tensorflow", "deep learning tensorflow"],
  },
  terraform: {
    id: "terraform",
    label: "Terraform",
    aliases: ["terraform", "hashicorp terraform", "iac terraform", "infrastructure as code terraform"],
  },
  tfs: {
    id: "tfs",
    label: "TFS",
    aliases: ["tfs", "team foundation server", "azure devops server", "tfvc", "tfs azure devops"],
  },
  typescript: {
    id: "typescript",
    label: "TypeScript",
    aliases: ["typescript", "ts"],
  },
  unix: {
    id: "unix",
    label: "Unix",
    aliases: ["unix", "unix operating system", "bsd unix", "linux unix-like", "posix system"],
  },
  vagrant: {
    id: "vagrant",
    label: "Vagrant",
    aliases: ["vagrant", "hashicorp vagrant", "vm provisioning vagrant"],
  },
  vault: {
    id: "vault",
    label: "Vault",
    aliases: ["vault", "hashicorp vault", "secrets management vault", "vault kv", "secret store vault"],
  },
  visualforce: {
    id: "visualforce",
    label: "Visualforce",
    aliases: ["visualforce", "salesforce visualforce", "vf pages", "salesforce ui framework"],
  },
  visualstudio: {
    id: "visualstudio",
    label: "Visual Studio",
    aliases: ["visual studio", "vs ide", "microsoft visual studio"],
  },
  vscode: {
    id: "vscode",
    label: "VS Code",
    aliases: ["visual studio code", "vscode", "vs code", "code editor vscode", "microsoft vscode"],
  },
  vite: {
    id: "vite",
    label: "Vite",
    aliases: ["vite", "vitejs", "vite.js"],
  },
  vitest: {
    id: "vitest",
    label: "Vitest",
    aliases: ["vitest"],
  },
  vmware: {
    id: "vmware",
    label: "VMware",
    aliases: ["vmware", "vmware esxi", "vmware vcenter", "virtualization vmware", "vmware workstation"],
  },
  voip: {
    id: "voip",
    label: "VoIP",
    aliases: ["voip", "voice over ip", "internet telephony", "sip voip", "softphone systems"],
  },
  vue: {
    id: "vue",
    label: "Vue.js",
    aliases: ["vue", "vuejs", "vue.js"],
  },
  vuex: {
    id: "vuex",
    label: "Vuex",
    aliases: ["vuex"],
  },
  webPerformance: {
    id: "web-performance",
    label: "Web Performance",
    aliases: [
      "performance",
      "web performance",
      "frontend performance",
      "performance optimization",
      "web vitals",
      "core web vitals",
    ],
  },
  websocket: {
    id: "websocket",
    label: "WebSocket",
    aliases: ["websocket", "websockets", "signalr"],
  },
  webpack: {
    id: "webpack",
    label: "Webpack",
    aliases: ["webpack"],
  },
  wordpress: {
    id: "wordpress",
    label: "WordPress",
    aliases: ["wordpress", "wp", "wordpress cms", "woocommerce wordpress", "content management wordpress"],
  },
  yarn: {
    id: "yarn",
    label: "Yarn",
    aliases: ["yarn"],
  },
  zend: {
    id: "zend",
    label: "Zend",
    aliases: ["zend", "zend framework", "laminas", "php zend", "zend engine"],
  },
  zod: {
    id: "zod",
    label: "Zod",
    aliases: ["zod"],
  },
  zookeeper: {
    id: "zookeeper",
    label: "ZooKeeper",
    aliases: ["zookeeper", "apache zookeeper", "distributed coordination zookeeper", "zk ensemble"],
  },
  zustand: {
    id: "zustand",
    label: "Zustand",
    aliases: ["zustand"],
  },
} as const;
